rem командный файл для создания библиотеки tbg_tcl.lib

del  tbg_tcl.lib

tlib tbg_tcl.lib +tbg_dat.obj

tlib tbg_tcl.lib +tbg_load.obj
tlib tbg_tcl.lib +tbg_del.obj

tlib tbg_tcl.lib +tbg_idx1.obj

tlib tbg_tcl.lib +tbg_tbl1.obj
tlib tbg_tcl.lib +tbg_tbl2.obj
tlib tbg_tcl.lib +tbg_tbl3.obj
tlib tbg_tcl.lib +tbg_tbl4.obj
tlib tbg_tcl.lib +tbg_tbl5.obj


tlib tbg_tcl.lib +tbg_dmxy.obj
tlib tbg_tcl.lib +tbg_smxy.obj

tlib tbg_tcl.lib +tbg_out0.obj
tlib tbg_tcl.lib +tbg_out1.obj
tlib tbg_tcl.lib +tbg_bins.obj
tlib tbg_tcl.lib +tbg_out2.obj
tlib tbg_tcl.lib +tbg_out3.obj
tlib tbg_tcl.lib +tbg_out4.obj
tlib tbg_tcl.lib +tbg_out5.obj
tlib tbg_tcl.lib +tbg_out6.obj

tlib tbg_tcl.lib +tbg_scl1.obj
tlib tbg_tcl.lib +tbg_scl2.obj

tlib tbg_tcl.lib +tbg_gcl.obj
tlib tbg_tcl.lib +tbg_gcls.obj
tlib tbg_tcl.lib +tbg_gsz1.obj

tlib tbg_tcl.lib +tbg_cmp1.obj
tlib tbg_tcl.lib +tbg_cmp2.obj

tlib tbg_tcl.lib +tbg_txt1.obj
tlib tbg_tcl.lib +tbg_txt2.obj
tlib tbg_tcl.lib +tbg_txt3.obj

tlib tbg_tcl.lib +tbg_get1.obj
tlib tbg_tcl.lib +tbg_get2.obj
tlib tbg_tcl.lib +tbg_get3.obj
tlib tbg_tcl.lib +tbg_get4.obj

tlib tbg_tcl.lib +tbg_set1.obj
tlib tbg_tcl.lib +tbg_set2.obj
tlib tbg_tcl.lib +tbg_set3.obj

tlib tbg_tcl.lib +tbg_pren.obj

tlib tbg_tcl.lib +tbg_chk1.obj
tlib tbg_tcl.lib +tbg_chk2.obj

tlib tbg_tcl.lib +tbg_mou0.obj
tlib tbg_tcl.lib +tbg_mou1.obj
tlib tbg_tcl.lib +tbg_mou2.obj
tlib tbg_tcl.lib +tbg_mou3.obj
tlib tbg_tcl.lib +tbg_mou4.obj
tlib tbg_tcl.lib +tbg_mou5.obj
tlib tbg_tcl.lib +tbg_mou6.obj
tlib tbg_tcl.lib +tbg_mou7.obj
tlib tbg_tcl.lib +tbg_mou8.obj
tlib tbg_tcl.lib +tbg_mou9.obj

tlib tbg_tcl.lib +tbg_rtt1.obj

tlib tbg_tcl.lib +tbg_err.obj

